---

- hosts: all
  become: yes
  tasks:
    - name: insatlling nginx using command
      command: apt install -y nginx
    - name: copying index.htm 
      command:  cp index.html  /var/www/html/index.html
    - name: restart nginx
      command: service nginx restart
              

