---
- hosts: all
  become: true
  tasks:
          
    - name: Installing Nginx and Mysql
      apt:
        name: 
         - nginx
         - php
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"   
 
