---
- hosts: all
  become: true
  tasks:
    - name: installing Nginx
      tags: nginx
      apt: name={{item}} state=latest
      with_items:
             - nginx
             - ncdu
    - name: updating default nginx file
      copy: 
       src: index.html 
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
    - name: restarting the service 
      service:
           name: nginx
           state: started
           enabled: yes
