---
- hosts: all
  become: true
  tasks:
          
    - name: uninstalling Nginx and php
      apt:
        name: 
         - nginx
         - php
         - apache2
        state: absent
        autoremove: yes
    
